on: [push, pull_request]
name: test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.18'
    - name: test
      run: make
    timeout-minutes: 10